'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Download, FileText, FileJson, FileImage, X } from 'lucide-react'

interface ExportPanelProps {
  data: {
    location: any
    terrain: any
    earthquakes: any
    geological: any
    bridgeDesigns?: any[]
  }
  onClose: () => void
}

export default function ExportPanel({ data, onClose }: ExportPanelProps) {
  const [exportFormat, setExportFormat] = useState<'json' | 'text' | 'pdf'>('json')
  const [isExporting, setIsExporting] = useState(false)
  
  // Generate bridge designs if not provided
  const bridgeDesigns = data.bridgeDesigns && data.bridgeDesigns.length > 0 
    ? data.bridgeDesigns 
    : generateBasicBridgeDesigns(data)

  const handleExport = async () => {
    setIsExporting(true)
    
    try {
      if (exportFormat === 'json') {
        exportAsJSON()
      } else if (exportFormat === 'text') {
        exportAsText()
      } else if (exportFormat === 'pdf') {
        await exportAsPDF()
      }
    } catch (error) {
      console.error('Export error:', error)
    } finally {
      setIsExporting(false)
    }
  }

  const exportAsJSON = () => {
    const jsonData = {
      location: data.location,
      analysis: {
        terrain: data.terrain,
        earthquakes: data.earthquakes,
        geological: data.geological,
      },
      bridgeDesigns: bridgeDesigns,
      exportedAt: new Date().toISOString(),
      version: '1.0'
    }

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `bridge-analysis-${data.location.name || 'location'}-${Date.now()}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const exportAsText = () => {
    const text = generateTextReport()
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `bridge-analysis-${data.location.name || 'location'}-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const exportAsPDF = async () => {
    // Create a simple HTML report and use browser print to PDF
    const htmlContent = generateHTMLReport()
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(htmlContent)
      printWindow.document.close()
      setTimeout(() => {
        printWindow.print()
      }, 250)
    }
  }

  const generateTextReport = (): string => {
    return `
BRIDGE DESIGN ANALYSIS REPORT
==============================

Location: ${data.location.name || 'Unknown'}
Coordinates: ${data.location.lat.toFixed(4)}°N, ${data.location.lng.toFixed(4)}°E
Date: ${new Date().toLocaleString()}

TERRAIN ANALYSIS
----------------
Elevation: ${data.terrain.elevation}m
Slope: ${data.terrain.slope}°
Terrain Type: ${data.terrain.terrainType}
Soil Type: ${data.terrain.soilType}
Landslide Risk: ${data.terrain.landslideRisk}

SEISMIC ACTIVITY
----------------
Total Earthquakes: ${data.earthquakes.total}
Recent (1 year): ${data.earthquakes.recent}
Max Magnitude: ${data.earthquakes.maxMagnitude.toFixed(1)}
Frequency: ${data.earthquakes.frequency}
Risk Level: ${data.earthquakes.riskLevel}

GEOLOGICAL FACTORS
------------------
Seismic Activity: ${data.geological.seismicActivity}
Fault Lines: ${data.geological.faultLines}
Rock Stability: ${data.geological.rockStability}
Erosion Risk: ${data.geological.erosionRisk}
Water Table: ${data.geological.waterTable}

BRIDGE DESIGNS
--------------
${bridgeDesigns.map((bridge: any, i: number) => `
${i + 1}. ${bridge.name || bridge.type || 'Bridge Design'}
   Type: ${bridge.type || 'N/A'}
   Suitability: ${bridge.suitability || 'N/A'}%
   ${bridge.estimatedCost ? `Cost: ₹${(bridge.estimatedCost / 10000000).toFixed(2)} Cr` : ''}
   ${bridge.lifespan ? `Lifespan: ${bridge.lifespan} years` : ''}
`).join('\n') || 'No bridge designs available'}

---
Report generated by GeoBridge AI
`
  }

  const generateHTMLReport = (): string => {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>Bridge Design Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
    h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #2563eb; color: white; }
    .metric { background-color: #f3f4f6; padding: 15px; margin: 10px 0; border-radius: 5px; }
    .bridge-card { border: 1px solid #ddd; padding: 15px; margin: 15px 0; border-radius: 5px; }
    @media print { button { display: none; } }
  </style>
</head>
<body>
  <h1>Bridge Design Analysis Report</h1>
  
  <div class="metric">
    <h3>Location Information</h3>
    <p><strong>Name:</strong> ${data.location.name || 'Unknown'}</p>
    <p><strong>Coordinates:</strong> ${data.location.lat.toFixed(4)}°N, ${data.location.lng.toFixed(4)}°E</p>
    <p><strong>Date:</strong> ${new Date().toLocaleString()}</p>
  </div>

  <h2>Terrain Analysis</h2>
  <table>
    <tr><th>Parameter</th><th>Value</th></tr>
    <tr><td>Elevation</td><td>${data.terrain.elevation}m</td></tr>
    <tr><td>Slope</td><td>${data.terrain.slope}°</td></tr>
    <tr><td>Terrain Type</td><td>${data.terrain.terrainType}</td></tr>
    <tr><td>Soil Type</td><td>${data.terrain.soilType}</td></tr>
    <tr><td>Landslide Risk</td><td>${data.terrain.landslideRisk}</td></tr>
  </table>

  <h2>Seismic Activity</h2>
  <table>
    <tr><th>Parameter</th><th>Value</th></tr>
    <tr><td>Total Earthquakes</td><td>${data.earthquakes.total}</td></tr>
    <tr><td>Recent (1 year)</td><td>${data.earthquakes.recent}</td></tr>
    <tr><td>Max Magnitude</td><td>${data.earthquakes.maxMagnitude.toFixed(1)}</td></tr>
    <tr><td>Frequency</td><td>${data.earthquakes.frequency}</td></tr>
    <tr><td>Risk Level</td><td>${data.earthquakes.riskLevel}</td></tr>
  </table>

  <h2>Geological Factors</h2>
  <table>
    <tr><th>Parameter</th><th>Value</th></tr>
    <tr><td>Seismic Activity</td><td>${data.geological.seismicActivity}</td></tr>
    <tr><td>Fault Lines</td><td>${data.geological.faultLines}</td></tr>
    <tr><td>Rock Stability</td><td>${data.geological.rockStability}</td></tr>
    <tr><td>Erosion Risk</td><td>${data.geological.erosionRisk}</td></tr>
    <tr><td>Water Table</td><td>${data.geological.waterTable}</td></tr>
  </table>

  <h2>Recommended Bridge Designs</h2>
  ${bridgeDesigns.map((bridge: any, i: number) => `
    <div class="bridge-card">
      <h3>${i + 1}. ${bridge.name || bridge.type || 'Bridge Design'}</h3>
      <p><strong>Type:</strong> ${bridge.type || 'N/A'}</p>
      <p><strong>Suitability:</strong> ${bridge.suitability || 'N/A'}%</p>
      ${bridge.estimatedCost ? `<p><strong>Estimated Cost:</strong> ₹${(bridge.estimatedCost / 10000000).toFixed(2)} Cr</p>` : ''}
      ${bridge.lifespan ? `<p><strong>Lifespan:</strong> ${bridge.lifespan} years</p>` : ''}
      ${bridge.annualMaintenance ? `<p><strong>Annual Maintenance:</strong> ₹${(bridge.annualMaintenance / 100000).toFixed(1)} L</p>` : ''}
      ${bridge.constructionTime ? `<p><strong>Construction Time:</strong> ${bridge.constructionTime} months</p>` : ''}
    </div>
  `).join('') || '<p>No bridge designs available</p>'}

  <hr>
  <p style="text-align: center; color: #666; margin-top: 30px;">
    Report generated by GeoBridge AI<br>
    ${new Date().toLocaleString()}
  </p>
  
  <button onclick="window.print()" style="padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 5px; cursor: pointer; margin-top: 20px;">
    Print / Save as PDF
  </button>
</body>
</html>
    `
  }

  return (
    <motion.div
      className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
    >
      <motion.div
        className="relative bg-white/10 backdrop-blur-xl rounded-2xl shadow-2xl w-full max-w-md border border-white/20 p-6"
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <Download className="w-6 h-6 text-blue-400" />
            <h2 className="text-xl font-bold text-white">Export Analysis</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 bg-white/10 hover:bg-white/20 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-white" />
          </button>
        </div>

        <div className="space-y-4">
          <div>
            <label className="text-sm font-semibold text-white mb-3 block">Select Format</label>
            <div className="space-y-2">
              {[
                { value: 'json', label: 'JSON', icon: FileJson, desc: 'Machine-readable data' },
                { value: 'text', label: 'Text Report', icon: FileText, desc: 'Human-readable report' },
                { value: 'pdf', label: 'PDF Document', icon: FileImage, desc: 'Print-ready format' },
              ].map((format) => {
                const Icon = format.icon
                return (
                  <button
                    key={format.value}
                    onClick={() => setExportFormat(format.value as any)}
                    className={`w-full p-4 rounded-lg border transition-all text-left ${
                      exportFormat === format.value
                        ? 'bg-blue-600/20 border-blue-500'
                        : 'bg-white/5 border-white/10 hover:border-white/20'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <Icon className={`w-5 h-5 ${exportFormat === format.value ? 'text-blue-400' : 'text-gray-400'}`} />
                      <div className="flex-1">
                        <div className="font-semibold text-white">{format.label}</div>
                        <div className="text-xs text-gray-400">{format.desc}</div>
                      </div>
                      {exportFormat === format.value && (
                        <div className="w-2 h-2 bg-blue-400 rounded-full" />
                      )}
                    </div>
                  </button>
                )
              })}
            </div>
          </div>

          <button
            onClick={handleExport}
            disabled={isExporting}
            className="w-full px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white rounded-lg flex items-center justify-center gap-2 transition-colors font-semibold"
          >
            {isExporting ? (
              <>
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                >
                  <Download className="w-5 h-5" />
                </motion.div>
                <span>Exporting...</span>
              </>
            ) : (
              <>
                <Download className="w-5 h-5" />
                <span>Export {exportFormat.toUpperCase()}</span>
              </>
            )}
          </button>
        </div>
      </motion.div>
    </motion.div>
  )
}

function generateBasicBridgeDesigns(data: any): any[] {
  const { earthquakes, terrain, geological } = data
  const designs = [
    {
      name: 'Suspension Bridge',
      type: 'Suspension',
      suitability: 75,
    },
    {
      name: 'Cable-Stayed Bridge',
      type: 'Cable-Stayed',
      suitability: 80,
    },
    {
      name: 'Arch Bridge',
      type: 'Arch',
      suitability: 70,
    },
    {
      name: 'Beam Bridge',
      type: 'Beam',
      suitability: 65,
    },
    {
      name: 'Truss Bridge',
      type: 'Truss',
      suitability: 72,
    },
  ]
  
  // Sort by suitability
  return designs.sort((a, b) => b.suitability - a.suitability)
}

